# Generated by Django 3.0 on 2019-12-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='comlete',
            new_name='complete',
        ),
    ]
