# Generated by Django 3.0 on 2019-12-02 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20191202_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='complete',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='desc',
            new_name='description',
        ),
    ]
